platform: x86

branches:
  only:
    - main

clone_folder: c:\projects\FlappyBird

configuration: Release

image:
  - Visual Studio 2019

install:
  - git submodule update --init --recursive

before_build:
  - cmd: |
      pip install pillow
      cd flappy_bird
      gen-atlasses.bat
      cd project/proj.cmake
      mkdir build
      cd build
      cmake -A Win32 -G "Visual Studio 16 2019" ..

build:
  parallel: true
  verbosity: normal

build_script: |
  cmake --build . --config Release

after_build:
  - cmd: cp -R ../../../data/* Release/
  - cmd: cd c:\projects\FlappyBird\flappy_bird\project\proj.cmake\build
  - cmd: 7z a FlappyBird.zip Release
  - cmd: mv FlappyBird.zip ../../../../FlappyBird.zip

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: FlappyBird.zip
    name: FlappyBird